// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SeleniumTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void seleniumTest() {
    driver.get("http://localhost:4200/login");
    driver.manage().window().setSize(new Dimension(1303, 717));
    driver.findElement(By.id("exampleInputEmail1")).click();
    driver.findElement(By.id("exampleInputEmail1")).sendKeys("Anjitha");
    driver.findElement(By.id("exampleInputPassword1")).click();
    driver.findElement(By.id("exampleInputPassword1")).sendKeys("Ajnj");
    driver.findElement(By.id("exampleCheck1")).click();
    driver.findElement(By.id("liveAlertBtn")).click();
    driver.findElement(By.cssSelector(".col-md-6 > .btn")).click();
    driver.findElement(By.cssSelector(".btn:nth-child(3)")).click();
    driver.findElement(By.cssSelector("#mat-radio-2 .mat-radio-outer-circle")).click();
    driver.findElement(By.cssSelector("#mat-radio-7 .mat-radio-outer-circle")).click();
    driver.findElement(By.cssSelector("#mat-radio-15 .mat-radio-outer-circle")).click();
    driver.findElement(By.cssSelector("#mat-radio-17 .mat-radio-inner-circle")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".mat-raised-button"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".mat-raised-button")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.cssSelector(".swal2-confirm")).click();
    driver.findElement(By.cssSelector(".mt20:nth-child(1) .btn")).click();
    driver.findElement(By.cssSelector(".btn-outline-success")).click();
    driver.findElement(By.cssSelector("app-add-questions > .input-group:nth-child(1) > .form-control")).click();
    driver.findElement(By.cssSelector("app-add-questions > .input-group:nth-child(1) > .form-control")).sendKeys("Java");
    driver.findElement(By.cssSelector(".input-group:nth-child(2) > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(2) > .form-control")).sendKeys("Java");
    driver.findElement(By.cssSelector(".input-group:nth-child(3) > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(3) > .form-control")).sendKeys("Java");
    driver.findElement(By.cssSelector(".input-group:nth-child(4) > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(4) > .form-control")).sendKeys("Java");
    driver.findElement(By.cssSelector(".input-group:nth-child(5) > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(5) > .form-control")).sendKeys("Java");
    driver.findElement(By.cssSelector(".input-group:nth-child(2) > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(2) > .form-control")).sendKeys("Javas");
    driver.findElement(By.cssSelector(".input-group:nth-child(3) > .form-control")).click();
    driver.findElement(By.cssSelector("app-add-questions > .input-group:nth-child(1)")).click();
    driver.findElement(By.cssSelector("app-add-questions > .input-group:nth-child(1) > .form-control")).sendKeys("Correct Spelling");
    driver.findElement(By.cssSelector(".input-group:nth-child(3) > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(3) > .form-control")).sendKeys("Jaba");
    driver.findElement(By.cssSelector(".input-group:nth-child(4) > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group:nth-child(4) > .form-control")).sendKeys("Javar");
    driver.findElement(By.cssSelector(".input-group > .input-group > .form-control")).click();
    driver.findElement(By.cssSelector(".input-group > .input-group > .form-control")).sendKeys("Java");
    driver.findElement(By.cssSelector(".input-group > .btn")).click();
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }
}
